server:
  port: 0

spring:
  application:
    name: user-service
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin123

  mail:
    host: smtp.naver.com # SMTP 서버 호스트
    port: 465 # SMTP 서버 포트
    username: ubing0101
    password:  # 앱 비밀번호 16자리 (공백없이)
    properties:
      mail:
        smtp:
          auth: true # 사용자 인증 시도 여부 (앱 비밀번호로 인증)
          timeout: 5000
          ssl:
            enable: true
            trust: smtp.naver.com
#          starttls:
#            enable: true 구글(gmail) 설정은 tls 사용 허용

# 카카오 로그인용 데이터
oauth2:
  kakao:
    client-id: 
    redirect-uri: http://localhost:8000/user-service/user/kakao

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health, busrefresh, beans

springdoc:
  api-docs:
    path: /v3/api-docs # default value
    groups:
      enabled: true # api 그룹화
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha # 태그 정렬 방식 (알파벳순)
    operations-sorter: alpha # 메서드 정렬 방식
    display-request-duration: true # 요청에 소요된 시간 표시
    doc-expansion: none # 문서 초기 펼침 상태